### ISSUE TITLE
What is the second numer next to the Username?

### ISSUE THREAD

**Issue by CoalaJoe** [CoalaJoe/RetroAchievements-API#1]
If anyone knows. Please tell me, I asumed it is the max points a user can get with the games he currently plays.

**Comment by coczero** [comment]
This would be the retro points. This is a second point value given to achievements indicating their "rarenes". This value will be higher according to number of players of the game and the ratio how much people have earned it.

**Comment by CoalaJoe** [comment]
Nice. Thanks alot!
